'''
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DO NOT EDIT THIS FILE
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'''

import io
from unittest import mock, TestCase

from tip_calc import bill_amount, number_of_people, tip_percentage, tip_calculator
# from tip_calc import *

class TestTipCalculator(TestCase):
    @mock.patch('builtins.input', return_value='15')
    @mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_bill_amount(self, mock_stdout, mock_input):
        num = bill_amount()

        self.assertEqual(15.0, num)
        # bill_amount()
        # self.assertEqual("Enter your bill amount in dollars: 15.0\n", mock_stdout.getvalue())
